FROM alpine:3.17

# Install system dependencies
RUN apk update && \
    apk add alpine-sdk git python3 py3-pip python3-dev gcc libc-dev bash zlib-dev librdkafka-dev

# Clone Github repo and python3 dependencies
RUN git clone https://github.com/ifnesi/pydatagen && \
    python3 -m pip install --upgrade pip && \
    python3 -m pip install --no-cache-dir -r pydatagen/requirements.txt

# Python script to publish data to Kafka (topic: user_behavior, 7 partitions)
#CMD ["python3", "pydatagen/pydatagen.py", "--schema-filename", "users_behavior.avro", "--keyfield", "user_id", "--topic", "user_behavior", "--bootstrap-servers", "broker:9094", "--schema-registry", "http://schema-registry:9081", "--interval", "100"]
