FROM alpine:3.17

# Install system dependencies
RUN apk update && \
    apk add alpine-sdk git python3 py3-pip python3-dev gcc libc-dev bash zlib-dev librdkafka-dev

# Clone Github repo and python3 dependencies
RUN git clone https://github.com/ifnesi/pydatagen && \
    python3 -m pip install --upgrade pip && \
    python3 -m pip install --no-cache-dir -r pydatagen/requirements.txt
